name: Generate pacman animation

on:
  schedule: # 12 saatte bir çalıştır
    - cron: "0 */12 * * *"
  workflow_dispatch: # Elle tetiklemek için
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 1. Adım: Resmi oluştur (Token ekledik!)
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Limit takılmaması için kritik satır

      # 2. Adım: Klasör oluştur ve tüm SVG'leri taşı
      - name: Move file to dist directory
        run: |
          mkdir -p dist
          mv *.svg dist/

      # 3. Adım: dist klasörünü output dalına yükle
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
